### ISSUE TITLE
AttributeError: GEOHAYSTACK

### ISSUE THREAD

**Issue by Mohsen-Khodabakhshi** [bdragon300/mongoengine-migrate#48]
Hi.
In MongoDB version 5.0 and newer `geoHaystack` indexes removed, actually in PyMongo version 4.0 and newer too.
Now mongoengine-migrate not working with PyMongo version 4.0 and newer, because in `actions/base.py` in line 611, you used `GEOHAYSTACK`.
The error is:
`AttributeError: module 'pymongo' has no attribute 'GEOHAYSTACK'`
[https://docs.mongodb.com/manual/core/geohaystack/](url)
[https://pymongo.readthedocs.io/en/4.0/api/pymongo/collection.html](url)

**Comment by bdragon300** [comment]
Hello, sorry for long answer. Looks good, merged. Thanks
